### ISSUE TITLE
User signups impossible after PHPBB 3.1.10

### ISSUE THREAD

**Issue by Retroity** [Derky/Sortables-CAPTCHA-Plugin#10]
This may be a PHPBB 3.1.10 thing, but when this extension is enabled, the "Confirmation of Registration" section and the section with the "Reset" and "Submit" buttons in the PHPBB signup page are hidden.

This is what this issue looks like:
![chrome_2016-11-29_17-30-24](https://cloud.githubusercontent.com/assets/20492094/20733544/8e06fe7e-b659-11e6-9c8d-473299de6159.png)

For reference, this is what the signup page looks like normally (with reCaptcha)
![chrome_2016-11-29_17-32-35](https://cloud.githubusercontent.com/assets/20492094/20733598/d353354c-b659-11e6-9e80-7719035d5717.png)

This seems to be an issue caused by PHPBB 3.1.10, as I've noticed that this PHPBB update has caused many issues with other extensions.

**Comment by Galixte** [comment]
Hi @Derky,

could you take a look, please ?

**Comment by Derky** [comment]
I just tested a clean install on 3.1.10 and that works. Are you sure you didn't accidentally deleted the contents of the /ext/ folder during the update?

**Comment by DrDeath** [comment]
Works also with phpBB 3.2
