### ISSUE TITLE
ACP Captcha panel blank if this Plugin is enabled.

### ISSUE THREAD

**Issue by heinrich-k** [Derky/Sortables-CAPTCHA-Plugin#12]
The ACP Panel where one would choose and config the captcha is not loading, but shows a blank page on Chrome.

phpbb 3.2.7
php PHP Version 7.0.33-0ubuntu0.16.04.5

**Comment by Galixte** [comment]
Hi @Derky,

could you take a look, please?

**Comment by Derky** [comment]
Please see this manual fix for now: https://www.phpbb.com/customise/db/extension/sortables_captcha/support/topic/203886?p=687376#p687376

**Comment by Derky** [comment]
Fixed in version 2.0.1
