### ISSUE TITLE
Duplicate Item bug?

### ISSUE THREAD

**Issue by bunkei** [Derky/Sortables-CAPTCHA-Plugin#14]
I've been able to duplicate this possible bug in all major browsers (Chrome, Firefox, Edge).  It doesn't matter how many items I use or the order I use them.  There's always one item that appears twice.  I'm using phpBB v3.2.8.  PHP version is 7.0.33.  I have 3 separate phpBB installations and they all have this bug:

![bug](https://user-images.githubusercontent.com/23413137/65392338-9e8d4700-dd28-11e9-95f1-070d7fc01584.png)

![bug2](https://user-images.githubusercontent.com/23413137/65392343-acdb6300-dd28-11e9-81d8-8661479fb7aa.png)

**Comment by Derky** [comment]
Continuing here: https://www.phpbb.com/customise/db/mod/sortables_captcha_plugin/support/topic/208001
