### ISSUE TITLE
not working with 3.3.0

### ISSUE THREAD

**Issue by hardlevel** [Derky/Sortables-CAPTCHA-Plugin#18]
Please update the plugin to work with the newest phpbb

I got this error but couldn't find out how to solve:

Exception: The file "/var/www/wordpress/forum/ext/derky/sortablescaptcha/config/services.yml" does not contain valid YAML: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 10 (near "- @dbal.conn").

#0 /var/www/wordpress/forum/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(117): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile('/var/www/wordpr...')
#1 /var/www/wordpress/forum/phpbb/extension/di/extension_base.php(99): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('services.yml')
#2 /var/www/wordpress/forum/phpbb/extension/di/extension_base.php(63): phpbb\extension\di\extension_base->load_services(Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#3 /var/www/wordpress/forum/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(71): phpbb\extension\di\extension_base->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#4 /var/www/wordpress/forum/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#5 /var/www/wordpress/forum/vendor/symfony/dependency-injection/Compiler/Compiler.php(140): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 /var/www/wordpress/forum/vendor/symfony/dependency-injection/ContainerBuilder.php(789): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 /var/www/wordpress/forum/phpbb/di/container_builder.php(203): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#8 /var/www/wordpress/forum/common.php(115): phpbb\di\container_builder->get_container()
#9 /var/www/wordpress/forum/adm/index.php(23): require('/var/www/wordpr...')
#10 {main}

**Comment by DrDeath** [comment]
See this PR:  https://github.com/Derky/Sortables-CAPTCHA-Plugin/pull/19

**Comment by Derky** [comment]
Fixed by merging #19
