### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by iozuniga** [Derky/Sortables-CAPTCHA-Plugin#20]
Version 2.0.2: (2020-02-19)

[phpBB Debug] PHP Warning: in file [ROOT]/ext/derky/sortablescaptcha/captcha/sortables.php on line 124: count(): Parameter must be an array or an object that implements Countable

**Comment by Derky** [comment]
Thanks for your report, what PHP version are you using exactly?

**Comment by iozuniga** [comment]
Hi,

Glad to help. The version is 7.3.26

Regards
--
Ignacio Ortiz de Zúñiga
Email: iozuniga@ozs.com

**Comment by Derky** [comment]
I managed to reproduce this warning by selecting a language on the registration page without having Sortables questions available in that language. The warning occurs before it falls back to the boards default language. 

You can fix this by configuring questions for every language, or by manually applying [this change](https://github.com/Derky/Sortables-CAPTCHA-Plugin/commit/9cd5492a04a172fcc93628601839e4415e64d1bf) which will be in the upcoming 2.0.3 release.

**Comment by iozuniga** [comment]
Hi,

Great news. I have already fixed the language issue. I did not realize that
was the cause of the problem. Thank you!

Regards,
--
Ignacio Ortiz de Zúñiga
Email: iozuniga@ozs.com
