### ISSUE TITLE
Unable to find template "@derky_sortablescaptcha/captcha_sortables.html"

### ISSUE THREAD

**Issue by K4sum1** [Derky/Sortables-CAPTCHA-Plugin#25]
```
PHP message: PHP Fatal error:  Uncaught Twig\Error\LoaderError: Unable to find template "@derky_sortablescaptcha/captcha_sortables.html" (looked into: ) in "ucp_register.html" at line 103. in /eclipse/board.eclipse.cx/vendor/twig/twig/src/Loader/FilesystemLoader.php:250
```

Not sure how bad the error is, but my server keeps randomly just quitting and giving 500 errors so I'm wanting to reduce the amount of errors in my log. I'm using 2.0.2, going to be upgrading to 2.0.3 by downloading master branch. Also using PHP 8.3.

Also my setup is using OpenBSD httpd which has a chroot in /var/www/. idk if it's trying to use an absolute path or something.

**Comment by K4sum1** [comment]
I haven't upgraded to 2.0.3 yet. Should I try this and not upgrade, or go through the upgrade process?

**Comment by Derky** [comment]
Try this first please

**Comment by K4sum1** [comment]
Ok, I did that. So far the rate seems to be one occurrence every day, so it might be a while before I get back. Not sure what or where the error comes from especially since it seemed to work fine when I tried it and users were able to register.

**Comment by Derky** [comment]
Ok good to hear. This shouldn't really happen automatically however, are you perhaps manually clearing some cache folders on your server?

**Comment by K4sum1** [comment]
So I looked again, and I have the error again. I also now noticed there's a stack trace and apparently there was one before but I guess I just didn't see it at the time and therefore didn't send. Error is maybe not an issue as the forum still works and the captcha also seems to work fine too still after it.

```
PHP message: PHP Fatal error:  Uncaught Twig\Error\LoaderError: Unable to find template "@derky_sortablescaptcha/captcha_sortables.html" (looked into: ) in "ucp_register.html" at line 103. in /eclipse/board.eclipse.cx/vendor/twig/twig/src/Loader/FilesystemLoader.php:250
Stack trace:
#0 /eclipse/board.eclipse.cx/phpbb/template/twig/loader.php(135): Twig\Loader\FilesystemLoader->findTemplate()
#1 /eclipse/board.eclipse.cx/vendor/twig/twig/src/Loader/FilesystemLoader.php(150): phpbb\template\twig\loader->findTemplate()
#2 /eclipse/board.eclipse.cx/vendor/twig/twig/src/Environment.php(299): Twig\Loader\FilesystemLoader->getCacheKey()
#3 /eclipse/board.eclipse.cx/vendor/twig/twig/src/Environment.php(381): Twig\Environment->getTemplateClass()
#4 /eclipse/board.eclipse.cx/phpbb/template/twig/environment.php(291): Twig\Environment->loadTemplate()
#5 /eclipse/board.eclipse.cx/vendor/twig/twig/src/Template.php(333): phpbb\template\twig\environment->loadTemplate()
#6 /eclipse/board.eclipse.cx/cache/productio...
```

**Comment by Derky** [comment]
I think that's an older error because it won't work if a fatal error occurs.

But good to hear it's now working again, this error can only really happen if you remove cache files manually or move, replace or update files of the extension without disabling and it before.

**Comment by K4sum1** [comment]
It's not an older error. There's three more of them than there were before when I made the previous comment.

**Comment by Derky** [comment]
Ah I see the problem now. You have an old subsilver2 style installed that's called "legacy". The captcha doesn't work with that and I'm getting an HTTP 500 error on your registration page because of that. It is working properly with prosilver-based styles.

**Comment by K4sum1** [comment]
That makes sense, and I can replicate that and get it to throw the error. Is there any way to fix this or have a fallback for the legacy theme?

**Comment by Derky** [comment]
Good to hear. You have to rewrite the HTML, CSS and JavaScript yourself to make it compatible if you want to keep using that style. I don't recommend using that style because it's probably also missing features and template events that were added in later versions of phpBB. So you will keep running into compatibility problems.
