### ISSUE TITLE
Multiple lists

### ISSUE THREAD

**Issue by Galixte** [Derky/Sortables-CAPTCHA-Plugin#7]
Hi @Derky,

is it possible to use some multiple lists for one same language ?

**Comment by Derky** [comment]
You can only sort between 2 columns by default. If you want to add more columns you'd have to edit the code.

**Comment by Galixte** [comment]
Hi @Derky,

i don’t talk about the columns but the SORTABLE LISTS to display one from several of these (with a aleatory mode).

**Comment by Derky** [comment]
Sorry for the late reply. By default it's possible to create a list per language:
![sortables_language](https://cloud.githubusercontent.com/assets/318762/11764309/012a2bbe-a12b-11e5-8912-523eab01c96d.png)

**Comment by Galixte** [comment]
ok thanks for answered.
