### ISSUE TITLE
Mobile devices

### ISSUE THREAD

**Issue by wcz-txp** [Derky/Sortables-CAPTCHA-Plugin#8]
This extension doesn't work on mobile devices.
Tested in Android with Opera and Chrome.

**Comment by Derky** [comment]
I cannot reproduce this on an Android device using Chrome. Are you sure you're using the latest version?

**Comment by wcz-txp** [comment]
Hello, 
phpbb 3.1.9
Sortables Captcha 2.0
Maybe it is linked to the used style https://www.phpbb.com/customise/db/style/allan_style_subsilver/

**Comment by Derky** [comment]
Yes, subsilver2-based styles are no longer supported. If you want to support it, you have to copy the prosilver files and adjust them yourself.

**Comment by Galixte** [comment]
Hi @Derky, the style https://www.phpbb.com/customise/db/style/allan_style_subsilver/ is a prosilver based style with a design like subSilver2. ;)

**Comment by wcz-txp** [comment]
I think, that I could bypass it.
**Allan Style Subsilver** (really a prosilver one) uses also the _jquery-ui.js_ (in an older version) and this is later loaded than the JS from the extension, so everything is redeclared and that's why the touch screen is not working.

According to this (in the last chapter)
https://www.phpbb.com/customise/db/style/allan_style_subsilver/support/topic/209836
and my own experience, one can use the style without loading this JS. And in this way one can avoid this problem on mobile devices.
